feat/authorization-mechanism
atls-academy/Nikitabkv.github.io pull request #5
Opened 2023-05-19 12:20 UTC by Nikitabkv

- created auth functions

- downgraded versions: 
  - eslint to 8.18
  - @types/eslint to 8

2023-05-19 18:12 UTC, TorinAsakura requested changes

2023-05-19 18:46 UTC, Nikitabkv commented on auth/login.ts
> +}
Речь про return'ы?
Уберу

2023-05-19 18:46 UTC, Nikitabkv commented on auth/login.ts
> +    currentUserData = {
Данные текущего пользователя, стоит переименовать просто в currentUser?

2023-05-19 19:02 UTC, Nikitabkv commented on auth/register.ts
> +import {IUser} from './user.interface'
Нашел "**Don't** prefix with `I`"
Исправлюсь

2023-05-20 08:26 UTC, TorinAsakura requested changes

2023-05-20 08:26 UTC, TorinAsakura commented on auth/login.ts
> +import {IUser} from './user.interface'
1. Названия переменных и функций: Старайся использовать более понятные и описательные названия. Например, вместо **credentials** можно использовать **users** или **userList**, а вместо **currentUserData** - **currentUser**.

2. Обработка ошибок: Вместо использования throw new Error для обработки ошибки, рекомендуется использовать механизм исключений (exceptions), дабы более явно указать тип ошибки. Например, создай свой собственный класс исключений, такой как invalid-login.exception, и выбрасывай его вместо использования throw new Error.

3. Валидация данных: Рекомендуется добавить проверки входных данных на null и undefined, а также на пустые строки или массивы, если это необходимо. Например, можно добавить проверку if (!username || !password) перед выполнением дополнительных проверок.

4. Область видимости: Вместо изменения значения **currentUserData** внутри функции, рекомендуется возвращать новый объект с обновленными данными. Таким образом, будет явно указано, что функция изменяет данные и не создает сайдэффекты.

5. Типизация: Мы должны ТОЧНО знать, что интерфейс IUser правильно определён и содержит все необходимые поля для пользователя. Также, рекомендуется добавить типы входных и выходных данных функции login.

2023-05-20 08:26 UTC, TorinAsakura commented on auth/login.ts
> +}
нет, речь именно про отсутствие пустой строки в конце файла…

2023-05-20 08:36 UTC, Nikitabkv commented on auth/login.ts
> +}
Принял

2023-05-22 17:42 UTC, TorinAsakura requested changes

2023-05-22 17:42 UTC, TorinAsakura commented on auth/authErrors.ts
> +export class AuthError extends Error {
файлы именуются через кебаб-кейс

2023-05-22 17:42 UTC, TorinAsakura commented on auth/login.ts
>  import {User} from './user.interface'
Твой код в целом выглядит нормально, но давай немного его улучшим:

1. Поправь обработку ошибок. Нет необходимости "ловить" ошибку и затем просто логировать её. Это не приносит пользы и просто вносит шум в код. Лучше просто выбросить ошибку и обработать её выше по стеку вызовов.
2. Проверку activeUser.isAuth можно заменить на проверку activeUser && activeUser.isAuth. Это гарантирует, что activeUser определён, перед тем как мы обращаемся к его свойству isAuth.
3. При невалидной аутентификации возвращаемый объект пользователя с пустыми полями может быть запутывающим. Возможно, было бы лучше просто вернуть null или undefined в этом случае.

2023-05-22 17:42 UTC, TorinAsakura commented on auth/logout.ts
>  import {User} from './user.interface'
Далее:

1. Зачем нам нужно возвращать объект пользователя с пустыми полями, если авторизация не прошла? Возвращение null или undefined вместо этого было бы более явным и понятным.
2. Метод findIndex может вернуть -1, если ничего не найдено. Мы должны обработать этот случай, иначе мы рискуем получить ошибку при попытке доступа к элементу массива по индексу -1.
3. Опять же, ловить и логировать ошибки в этом контексте не имеет большого смысла. Это приводит к потере стека вызовов и усложняет отладку. Лучше просто выбросить ошибку и обработать её на более высоком уровне.

2023-05-22 17:42 UTC, TorinAsakura commented on auth/register.ts
> +import {AuthError} from "./authErrors"
Мои рекомендации остаются актуальными и для этого сценария. Кроме того, заметь, что существующие пользователи могут "перерегистрироваться" с тем же именем пользователя, что может вызвать проблемы.

2023-05-22 17:42 UTC, TorinAsakura commented on auth/whoami.ts
> +export const whoami = (activeUser: User) => {
Снова, хорошо бы возвращать информацию вместо пустого возврата в случае успешного выполнения функции. Поскольку функция названа whoami, ожидается, что она вернет информацию о текущем активном пользователе. Исключение может быть выброшено, если пользователь не авторизован.

2023-05-22 21:40 UTC, Nikitabkv commented on auth/register.ts
> +import {AuthError} from "./authErrors"
Не совсем понял момент с перерегистрацией
Вроде есть же проверка 
`if (userList.some(user => user.username === username)) throw AuthError.ValidationError( 'Username: "${username}" is already registered' )`

2023-05-22 21:42 UTC, TorinAsakura commented on auth/register.ts
> +import {AuthError} from "./authErrors"
Что-то в духе

```typescript
export const register = (username: string, password: string, userList: Array<User>, activeUser: User) : User | null => {
    if (activeUser.isAuth) throw AuthError.AuthError(`Тебе нужно выйти, прежде чем регистрировать новый аккаунт`)
    if (!username || !password) throw AuthError.ValidationError(`Логин или пароль не могут быть пустыми`)
    if (username.length <= 5) throw AuthError.ValidationError(`Логин должен быть длиннее 5 символов`)
    if (password.length <= 6) throw AuthError.ValidationError(`Пароль должен быть длиннее 6 символов`)
    if (userList.some(user => user.username === username)) throw AuthError.ValidationError(`Имя пользователя "${username}" уже зарегистрировано`)

    const newUser = {
        username,
        password,
        isAuth: true,
    }

    userList.push(newUser)

    return newUser
}
```

2023-05-22 22:30 UTC, Nikitabkv commented on auth/whoami.ts
> +export const whoami = (activeUser: User) => {
Я забыл, что по заданию whoami должен в консоль выводить логин, докинуть консоль или все же return пользователя сделать?

2023-05-22 23:38 UTC, TorinAsakura commented on auth/whoami.ts
> +export const whoami = (activeUser: User) => {
Сам смотри) Я уже вроде всё расписал, тебе надо просто сделать

2023-05-24 21:30 UTC, TorinAsakura requested changes
При работе с пользователями и их авторизацией обычно не рекомендуется хранить пароли в открытом виде. Даже если это просто демонстрационный код, хорошей практикой будет использовать какую-то форму хеширования для паролей.

В функции register ты добавляешь нового пользователя в массив пользователей (userList) и немедленно его авторизуешь. Но возвращаемый объект пользователя не ссылается на тот же объект, что был добавлен в userList. Это может привести к неожиданным результатам, если в дальнейшем ты решишь изменить состояние авторизации возвращаемого объекта пользователя. Предлагаю сделать что-то вроде:

```typescript
Copy code
const newUser = {
    username,
    password,
    isAuth: true,
}

userList.push(newUser)

return newUser
```

В функциях login и logout ты возвращаешь новый объект пользователя вместо изменения состояния существующего объекта пользователя в userList. Это может вызвать проблемы с синхронизацией состояния пользователей, если где-то еще в коде будет ссылка на этого пользователя. Я бы рекомендовал обновлять состояние существующего объекта пользователя в userList, а затем возвращать этот же объект.

В функциях login, logout и register проверка наличия активного пользователя и его состояния авторизации производится без проверки на null или undefined. Это может привести к ошибкам, если activeUser не передан. Лучше добавить проверку на null или undefined перед проверкой свойства isAuth.

В функции logout ты меняешь isAuth у пользователя в userList, но также возвращаешь новый объект пользователя. Это может привести к несогласованности данных. Если функция logout предназначена для изменения состояния пользователя в userList, лучше возвращать ссылку на этого же пользователя из списка, а не новый объект.

В функциях login и register нет необходимости возвращать пароль в объекте пользователя. Это не безопасно и обычно не требуется при работе с пользователями после их авторизации.

2023-05-24 21:30 UTC, TorinAsakura commented on tsconfig.json
> +}
последняя строка

2023-05-26 22:51 UTC, TorinAsakura approved these changes

2023-05-26 22:51 UTC, merged